training:
  max_steps: 3000
  grad_agg_freq: 1
  rec_results_freq: 1000
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  save_network_freq: 1000
  print_stats_freq: 200
  summary_freq: 1000
  grad_clip_max_norm: 1e9
  monitor_grad_clip: false
  ntk:
    use_ntk: false
    save_name: null
    run_freq: 1000
amp:
  enabled: false
  mode: per_order_scaler
  dtype: float16
  autocast_activation: false
  autocast_firstlayer: false
  default_max_scale_log2: 0
  custom_max_scales_log2: {}
graph:
  func_arch: true
  func_arch_allow_partial_hessian: true
stop_criterion:
  metric: null
  min_delta: null
  patience: 50000
  mode: min
  freq: 1000
  strict: false
profiler:
  profile: false
  start_step: 0
  end_step: 100
  name: nvtx
network_dir: outputs
initialization_network_dir: ''
save_filetypes: vtk
summary_histograms: 'off'
jit: false
jit_use_nvfuser: false
jit_arch_mode: only_activation
jit_autograd_nodes: false
cuda_graphs: false
cuda_graph_warmup: 20
find_unused_parameters: false
broadcast_buffers: false
device: ''
debug: false
run_mode: train
arch:
  fully_connected:
    arch_type: fully_connected
    input_keys: [{name: x, size: 1}]
    output_keys: [{name: u, size: 1}]
    detach_keys: []
    scaling: null
    layer_size: 100
    nr_layers: 3
    skip_connections: false
    activation_fn: tanh
    adaptive_activations: false
    weight_norm: false
models: {}
loss:
  _target_: physicsnemo.sym.loss.aggregator.Sum
  weights:
    interior: 1.0
    BC: 100.0
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1.0e-08
  weight_decay: 0.0
  amsgrad: false
  _params_:
    compute_gradients: adam_compute_gradients
    apply_gradients: adam_apply_gradients

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR   # ← PyTorch와 동일
  step_size: 1000
  gamma: 0.9
batch_size:
  Interior: ${data.N_R}
  BC: ${data.N_B}
data:
  x_min: -1.0
  x_max:  1.0
  N_R: 100
  N_B: 2
  N_test: 1000
custom:
  use_fourier: true
  fourier:
    m: 10
    std: 3.0
    include_raw_x: false